apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
  annotations:
    app.kubernetes.io/version: "v1.0.0"  # This will be replaced by GitHub Actions
    app.kubernetes.io/created-by: "github-actions"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      containers:
        - name: app
          image: ghcr.io/kyowanghwe/spring-boot-k8s:d20a4f235f3ef612cd4d93a73ece62740e9582e6
          ports:
            - containerPort: 8080