name: CI/CD to GHCR

on: [push]

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/kyowanghwe/spring-boot-k8s:latest .
          docker tag ghcr.io/kyowanghwe/spring-boot-k8s:latest ghcr.io/kyowanghwe/spring-boot-k8s:${{ github.sha }}

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: kyowanghwe
          password: ${{ secrets.GHCR_PAT }}

      - name: Push to GHCR
        run: |
          docker push ghcr.io/kyowanghwe/spring-boot-k8s:latest
          docker push ghcr.io/kyowanghwe/spring-boot-k8s:${{ github.sha }}

      - name: Update image tag in deployment.yaml
        run: |
          sed -i "s|ghcr.io/kyowanghwe/spring-boot-k8s:.*|ghcr.io/kyowanghwe/spring-boot-k8s:${{ github.sha }}|g" k8s/deployment.yaml

      - name: Commit and push updated deployment.yaml
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add k8s/deployment.yaml
          git commit -m "ci: update image tag to ${{ github.sha }}"
          git push    
