name: CI/CD to GHCR

on: [push]

permissions:
  contents: write     # needed to push changes to the repo
  packages: write     # needed to push to GHCR

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: ☕ Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: 🛠️ Build with Maven
        run: |
          echo "::group::Maven Build"
          mvn clean package -DskipTests
          echo "::endgroup::"

      - name: 🐳 Build Docker image
        run: |
          echo "::group::Docker Build"
          VERSION_TAG=$(date +'%Y%m%d-%H%M')-${GITHUB_SHA::7}
          echo "VERSION_TAG=$VERSION_TAG" >> $GITHUB_ENV
          docker build -t ghcr.io/kyowanghwe/spring-boot-k8s:latest .
          docker tag ghcr.io/kyowanghwe/spring-boot-k8s:latest ghcr.io/kyowanghwe/spring-boot-k8s:$VERSION_TAG
          echo "::endgroup::"

      - name: 🔐 Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: kyowanghwe
          password: ${{ secrets.GHCR_PAT }}

      - name: 📤 Push image to GHCR
        run: |
          echo "::group::Push Docker Image"
          docker push ghcr.io/kyowanghwe/spring-boot-k8s:latest
          docker push ghcr.io/kyowanghwe/spring-boot-k8s:$VERSION_TAG
          echo "::endgroup::"

      - name: 📝 Update deployment.yaml with new image tag and version annotation
        run: |
          echo "::group::Update deployment.yaml"
          sed -i "s|ghcr.io/kyowanghwe/spring-boot-k8s:.*|ghcr.io/kyowanghwe/spring-boot-k8s:${{ env.VERSION_TAG }}|g" k8s/deployment.yaml
          sed -i "s|app.kubernetes.io/version: .*|app.kubernetes.io/version: \"${{ env.VERSION_TAG }}\"|g" k8s/deployment.yaml
          echo "::endgroup::"

      - name: ✅ Commit and push updated deployment.yaml
        run: |
          echo "::group::Git Commit & Push"
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          
          git add k8s/deployment.yaml
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "ci: update image tag to ${{ github.sha }}"
            git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }} HEAD:main
          fi
          echo "::endgroup::"
